facts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^^product$', views.product_list, name='product_list'),
    url(r'^product/([0-9]{13})$', views.product_detail, name='product_detail'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('facts.urls')),
]

facts/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    key = models.PositiveIntegerField(primary_key=True)

    name = models.CharField(max_length=60)
    manufacturer = models.CharField(max_length=60)
    barcode = models.PositiveIntegerField()


class NutriFact(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    key = models.AutoField(primary_key=True)

    servingSize = models.FloatField()
    servingUM = models.CharField(max_length=4)
    servingQuantity = models.FloatField()
    servingQtdUm = models.CharField(max_length=4)
    footNote = models.TextField()


class NutriTable(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    key = models.AutoField(primary_key=True)

    componentID = models.CharField(max_length=60)
    componentQuantity = models.FloatField()
    componentUM = models.CharField(max_length=4)
    dailyValues = models.FloatField()

facts/views.py
from django.shortcuts import render

from facts.DataAccess import DataAccess
from .models import Product
from .models import NutriFact
from .models import NutriTable

# Create your views here.


def index(request):

    return render(request, 'facts/index.html')


def product_list(request):
    all_data = DataAccess()
    all_data.all_products()
    products = all_data.products
    facts = all_data.facts
    table = all_data.table.order_by('componentID')

    return render(request, 'facts/product_list.html', {'products': products,
                                                       'facts': facts,

                                                       'table': table})


def product_detail(request, barcode):
    products = Product.objects.filter(barcode=barcode)
    if len(products) > 0:
        for prod in products:
            facts = NutriFact.objects.filter(product=prod.key)
            table = NutriTable.objects.filter(product=prod.key).order_by('componentID')

    return render(request, 'facts/product_detail.html', {'products': products,
                                                         'facts': facts,
                                                         'table': table})

facts/templates/facts/index.html
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <title>NutriFacts</title>
</head>

<body>
    <div>
        <a href="http://127.0.0.1:8000/product">List of all products</a>
        <br>
        <a href="http://127.0.0.1:8000/product/7896016601965 ">Detail of barcode [7896016601965]</a>
    </div>
<body>

</body>
</html>

facts/templates/facts/product_detail.html
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <title>NutriFacts</title>
</head>
<body>
<!-- Header -->
<div>
    <h1><a href="">NutriFacts - Details</a></h1>
</div>

<div>
    <a href="/">[ Home ]</a>
    <a href="/product">[ Full list ]</a>
</div>

    {% for prod in products %}
<div>
    <hr>
    <p>Product: [ {{ prod.name }} ]</p>
    <p>{{ prod.manufacturer }}</p>
    <i>{{ prod.barcode }}</i>
</div>  <!-- Products -->

<div>
    <table>
        <tr>
            <th align="left"> Description </th>
            <th align="left"> Value </th>
        </tr>
        {% for fact in facts %}
        <tr>
            <td> Size </td>
            <td> {{ fact.servingSize }} </td>
        </tr><tr>
        <td> Product </td>
        <td> &nbsp; </td>
    </tr><tr>
        <td> UM </td>
        <td> {{ fact.servingUM }} </td>
    </tr><tr>
        <td> Quantity </td>
        <td> {{ fact.servingQuantity }} </td>
    </tr><tr>
        <td> UM </td>
        <td> {{ fact.servingQtdUm }} </td>
    </tr><tr>
        <td> Foot note </td>
        <td> {{ fact.footNote|linebreaksbr }} </td>
    </tr>
        {% endfor %}

    </table>
</div> <!-- Nutri Fact -->

<div>
    <table>
        <tr>
            <th> Component </th>
            <th> Value </th>
            <th align="center"> UM </th>
            <th align="right">Daily Values</th>
        </tr>
        {% for tab in table %}
        <tr>
            <td> {{ tab.componentID }} </td>
            <td> {{ tab.componentQuantity }} </td>
            <td align="center"> {{ tab.componentUM }} </td>
            <td align="right"> {{ tab.dailyValues }} </td>
        </tr>
        {% endfor %}
    </table>
</div> <!-- Nutri Table -->
{% endfor %}

</body>
</html>
</html>

facts/templates/facts/product_list.html
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <title>NutriFacts</title>
</head>
<body>
    <!-- Header -->
    <div>
        <h1><a href="">NutriFacts - Full list</a></h1>
    </div>
    <div>
        <a href="/">[ Home ]</a>
        <a href="/product">[ Full list ]</a>
    </div>
       {% for prod in products %}
    <div>
        <hr>
        <p>Product: [ {{ prod.name }} ]</p>
        <p>{{ prod.manufacturer }}</p>
        <p>
            <a href="product/{{ prod.barcode }}">{{ prod.barcode }}</a>
        </p>
    </div>  <!-- Products -->

    <div>
        <table>
            <tr>
                <th align="left"> Description </th>
                <th align="left"> Value </th>
            </tr>
            {% for fact in prod.nutrifact_set.all %}
            <tr>
                <td> Size </td>
                <td> {{ fact.servingSize }} </td>
            </tr><tr>
                <td> Product </td>
                <td> {{ prod.key }} </td>
            </tr><tr>
                <td> UM </td>
                <td> {{ fact.servingUM }} </td>
            </tr><tr>
                <td> Quantity </td>
                <td> {{ fact.servingQuantity }} </td>
            </tr><tr>
                <td> UM </td>
                <td> {{ fact.servingQtdUm }} </td>
            </tr><tr>
                <td> Foot note </td>
                <td> {{ fact.footNote|linebreaksbr }} </td>
            </tr>
            {% endfor %}

        </table>
    </div> <!-- Nutri Fact -->

    <div>
        <table>
            <tr>
                <th> Component </th>
                <th> Value </th>
                <th align="center"> UM </th>
                <th align="right">Daily Values</th>
            </tr>
            {% for tab in prod.nutritable_set.all %}
            <tr>
                <td> {{ tab.componentID }} </td>
                <td> {{ tab.componentQuantity }} </td>
                <td align="center"> {{ tab.componentUM }} </td>
                <td align="right"> {{ tab.dailyValues }} </td>
            </tr>
            {% endfor %}
        </table>
    </div> <!-- Nutri Table -->
    {% endfor %}

</body>
</html>
</html>